"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import toast from "react-hot-toast";
import { AdminDialog } from "@/components/admin/admin-dialog";
import { StatusBadge } from "@/components/admin/badges";
import { api } from "@/lib/api";

type Report = { id: string; entityType: string; priority: number; reason: string; description: string | null; status: string; createdAt: string; vendor: { name: string; area: string } | null; user: { name: string | null; trustScore: number }; assignedTo: { name: string | null } | null };
export default function ReportsPage() {
  const [status, setStatus] = useState(""); const [type, setType] = useState(""); const [pending, setPending] = useState<{ report: Report; status: "RESOLVED" | "DISMISSED" } | null>(null);
  const query = useQuery({ queryKey: ["admin-reports", status, type], queryFn: () => api<{items: Report[]; total: number}>(`/api/admin/reports?status=${status}&type=${type}`) });
  const submit = async (values: Record<string, string>) => { if (!pending) return; try { await api(`/api/admin/reports/${pending.report.id}/resolve`, { method: "POST", body: JSON.stringify({ status: pending.status, resolutionType: values.resolutionType, note: values.note || undefined }) }); toast.success(pending.status === "RESOLVED" ? "Report resolved" : "Report rejected"); await query.refetch(); } catch (error) { toast.error(error instanceof Error ? error.message : "Action failed"); throw error; } };
  return <div><h1 className="text-4xl font-black">Reports inbox</h1><p className="mt-2 text-stone-600">A unified moderation queue for vendors, reviews and photos.</p><div className="card mt-6 grid gap-3 p-4 sm:grid-cols-2"><select aria-label="Report status" className="field" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{["OPEN","REVIEWING","RESOLVED","DISMISSED"].map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Content type" className="field" value={type} onChange={(event) => setType(event.target.value)}><option value="">All content types</option>{["VENDOR","REVIEW","PHOTO"].map((item) => <option key={item}>{item}</option>)}</select></div><div className="mt-6 space-y-4">{query.data?.items.map((report) => <article className="card p-5" key={report.id}><div className="flex flex-wrap justify-between gap-3"><div><div className="flex gap-2"><StatusBadge value={report.status}/><span className="chip">{report.entityType}</span>{report.priority > 0 && <span className="chip">Priority {report.priority}</span>}</div><h2 className="mt-3 text-xl font-black">{report.reason}</h2><p className="mt-1 text-stone-600">{report.description || "No description"}</p></div><div className="text-right text-sm"><b>{report.vendor?.name || "Linked content"}</b><p>{report.vendor?.area}</p><p className="text-stone-500">Reporter: {report.user.name || "Anonymous"} · trust {report.user.trustScore}</p></div></div>{!["RESOLVED","DISMISSED"].includes(report.status) && <div className="mt-4 flex gap-2"><button className="btn-primary !min-h-9 !px-4" onClick={() => setPending({ report, status: "RESOLVED" })}>Resolve</button><button className="btn-secondary !min-h-9 !px-4" onClick={() => setPending({ report, status: "DISMISSED" })}>Reject</button></div>}</article>)}</div>
    <AdminDialog open={Boolean(pending)} title={pending?.status === "RESOLVED" ? "Resolve report" : "Reject report"} description={pending?.report.reason} confirmLabel={pending?.status === "RESOLVED" ? "Resolve" : "Reject"} danger={pending?.status === "DISMISSED"} onClose={() => setPending(null)} onSubmit={submit} fields={[{ name: "resolutionType", label: "Resolution", type: "select", defaultValue: "no_action", options: [{ value: "no_action", label: "No action needed" }, { value: "vendor_removed", label: "Vendor removed" }, { value: "review_removed", label: "Review removed" }, { value: "photo_removed", label: "Photo removed" }] }, { name: "note", label: "Internal note", type: "textarea", placeholder: "What was checked and decided?" }]}/>
  </div>;
}
