"use client";

import Image from "next/image";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import toast from "react-hot-toast";
import { ActionButton } from "@/components/admin/action-button";
import { AdminDialog } from "@/components/admin/admin-dialog";
import { StatusBadge, TrustBadge, VerificationBadge } from "@/components/admin/badges";
import { api } from "@/lib/api";

type Pending = { type: "verification"; level: number } | { type: "spam"; reviewId: string } | null;
export default function VendorDetailPage() {
  const { id } = useParams<{ id: string }>(); const [pending, setPending] = useState<Pending>(null);
  const query = useQuery({ queryKey: ["admin-vendor", id], queryFn: () => api<any>(`/api/admin/vendors/${id}`) }); const vendor = query.data;
  const post = async (url: string, body: unknown) => { try { await api(url, { method: "POST", body: JSON.stringify(body) }); toast.success("Updated"); await query.refetch(); } catch (error) { toast.error(error instanceof Error ? error.message : "Action failed"); throw error; } };
  const submit = async (values: Record<string, string>) => { if (pending?.type === "verification") await post(`/api/admin/vendors/${id}/verification`, { level: pending.level, notes: values.notes || undefined }); if (pending?.type === "spam") await post(`/api/admin/reviews/${pending.reviewId}/moderate`, { action: "spam", reason: values.reason }); };
  if (!vendor) return <div className="card p-10">Loading vendor…</div>;
  return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-4xl font-black">{vendor.name}</h1><p className="mt-2 text-stone-600">{vendor.address} · {vendor.area}, {vendor.zone}</p></div><div className="flex flex-wrap gap-2"><Link className="btn-secondary !min-h-9 !px-3" href={`/vendor/${id}/edit`}>Edit vendor</Link><VerificationBadge level={vendor.verificationLevel}/><StatusBadge value={vendor.status}/></div></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-3"><section className="card p-5 xl:col-span-2"><h2 className="text-xl font-black">Verification & ratings</h2><div className="mt-4 grid gap-4 sm:grid-cols-4">{[["Simple",vendor.ratingAvg],["Weighted",vendor.weightedRatingAvg],["Reviews",vendor.ratingCount],["Trusted reviews",vendor.trustedReviewCount]].map(([label,value]) => <div key={String(label)}><p className="text-xs text-stone-500">{label}</p><b className="text-2xl">{typeof value === "number" && String(label).includes("rating") ? value.toFixed(2) : value}</b></div>)}</div><p className="mt-4 rounded-2xl bg-orange-50 p-4 text-sm">{vendor.verificationNotes || "No internal verification notes."}</p><div className="mt-4 flex flex-wrap gap-2">{[0,1,2,3].map((level) => <button className="btn-secondary !min-h-9 !px-3 text-sm" key={level} onClick={() => setPending({ type: "verification", level })}>Set L{level}</button>)}<ActionButton url={`/api/admin/vendors/${id}/recompute-rating`} label="Recompute rating" onDone={() => query.refetch()}/></div></section>
      <section className="card p-5"><h2 className="text-xl font-black">Location</h2><div className="mt-4 overflow-hidden rounded-2xl border bg-orange-50"><iframe title="Map preview" className="h-52 w-full" src={`https://www.openstreetmap.org/export/embed.html?bbox=${vendor.lng-0.01}%2C${vendor.lat-0.01}%2C${vendor.lng+0.01}%2C${vendor.lat+0.01}&marker=${vendor.lat}%2C${vendor.lng}`}/></div><p className="mt-3 text-sm">Added by <b>{vendor.addedBy.name || "Unknown"}</b> · trust {vendor.addedBy.trustScore}</p></section></div>
    <section className="card mt-6 overflow-x-auto"><h2 className="p-5 text-xl font-black">Reviews</h2><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-orange-50"><tr>{["User","Rating","Comment","Flags","Actions"].map((heading) => <th className="p-4" key={heading}>{heading}</th>)}</tr></thead><tbody>{vendor.reviews.map((review: any) => <tr className="border-t" key={review.id}><td className="p-4"><p className="font-bold">{review.user.name || "Unnamed"}</p><TrustBadge trusted={review.user.isTrustedContributor} score={review.user.trustScore}/></td><td className="p-4">★ {review.rating} · weight {review.user.isTrustedContributor ? 2 : 1}</td><td className="max-w-md p-4">{review.comment}</td><td className="p-4">{review.isSpam ? "Spam" : review.isHidden ? "Hidden" : "Visible"}</td><td className="p-4"><div className="flex gap-2"><button onClick={() => void post(`/api/admin/reviews/${review.id}/moderate`, { action: review.isHidden ? "show" : "hide", reason: "Vendor detail moderation" })}>{review.isHidden ? "Show" : "Hide"}</button><button className="text-red-700" onClick={() => setPending({ type: "spam", reviewId: review.id })}>Spam</button></div></td></tr>)}</tbody></table></section>
    <section className="card mt-6 p-5"><h2 className="text-xl font-black">Photos</h2><div className="mt-4 grid gap-4 sm:grid-cols-3 xl:grid-cols-5">{vendor.photos.map((photo: any) => <div key={photo.id}><div className="relative aspect-square overflow-hidden rounded-2xl bg-orange-50"><Image fill className="object-cover" src={photo.photoUrl} alt={photo.caption || "Vendor photo"}/></div><button className="mt-2 text-sm text-red-700" onClick={() => void post(`/api/admin/photos/${photo.id}/moderate`, { action: photo.isHidden ? "show" : "hide", reason: "Vendor photo moderation" })}>{photo.isHidden ? "Show" : "Hide"}</button></div>)}</div></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="card p-5"><h2 className="text-xl font-black">Reports</h2>{vendor.reports.map((report: any) => <div className="mt-3 rounded-2xl bg-orange-50 p-4" key={report.id}><div className="flex justify-between"><b>{report.reason}</b><StatusBadge value={report.status}/></div><p className="mt-1 text-sm">{report.description}</p>{!["RESOLVED","DISMISSED"].includes(report.status) && <button className="mt-2 text-sm font-bold text-emerald-700" onClick={() => void post(`/api/admin/reports/${report.id}/resolve`, { status: "RESOLVED", resolutionType: "no_action", note: "Resolved from vendor view" })}>Resolve</button>}</div>)}</section><section className="card p-5"><h2 className="text-xl font-black">Activity log</h2>{vendor.activity.map((activity: any) => <div className="border-b py-3 text-sm" key={activity.id}><b>{activity.action.replaceAll("_", " ")}</b><p className="text-stone-500">{activity.user.name || "System"} · {new Date(activity.createdAt).toLocaleString()}</p>{activity.reason && <p>{activity.reason}</p>}</div>)}</section></div>
    <AdminDialog open={pending?.type === "verification"} title={`Set verification level ${pending?.type === "verification" ? pending.level : ""}`} description="Add the evidence checked for this level change." confirmLabel="Update verification" onClose={() => setPending(null)} onSubmit={submit} fields={[{ name: "notes", label: "Internal notes", type: "textarea", placeholder: "Call, visit, community evidence…" }]}/>
    <AdminDialog open={pending?.type === "spam"} title="Mark review as spam?" description="The review will be hidden, the contributor penalized, and ratings recomputed." confirmLabel="Mark spam" danger onClose={() => setPending(null)} onSubmit={submit} fields={[{ name: "reason", label: "Reason", type: "textarea", required: true }]}/>
  </div>;
}
